[package]
name = "phploc"
version = "0.1.0"
authors = ["Alessandro Benoit <micc83@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
